In [1]:
import torch
import numpy as np
import numpy
import matplotlib.pyplot as plt
import re
from sklearn.metrics import accuracy_score
import pandas as pd
import tensorflow as tf
from keras.utils import to_categorical
from sklearn.model_selection import train_test_split
from sklearn import datasets
import ast

In [2]:
i=100
x,y=[],[]
while i<=400:
    f=pd.read_csv('./samples/'+str(i)+'.csv',delimiter='\t')
    x.append(f)
    i+=50
y.append(pd.read_csv('./samples/test_280',delimiter='\t'))
y[0].drop(['channel','experimental','smoothed','Au','197Au'],axis=1,inplace=True)
for i in range(len(x)):
    x[i].drop(['channel','experimental','smoothed','Au','197Au'],axis=1,inplace=True)
for i in range(len(x)):
    x[i] = x[i].to_numpy()
y = y[0].to_numpy()
x

[array([[0.        ],
        [0.        ],
        [0.        ],
        ...,
        [0.05017025],
        [0.0230097 ],
        [0.00914428]]),
 array([[0.        ],
        [0.        ],
        [0.        ],
        ...,
        [0.05017025],
        [0.0230097 ],
        [0.00914428]]),
 array([[0.        ],
        [0.        ],
        [0.        ],
        ...,
        [0.05017025],
        [0.0230097 ],
        [0.00914428]]),
 array([[0.        ],
        [0.        ],
        [0.        ],
        ...,
        [0.05017025],
        [0.0230097 ],
        [0.00914428]]),
 array([[0.        ],
        [0.        ],
        [0.        ],
        ...,
        [0.05017025],
        [0.0230097 ],
        [0.00914428]]),
 array([[0.        ],
        [0.        ],
        [0.        ],
        ...,
        [0.05017025],
        [0.0230097 ],
        [0.00914428]]),
 array([[0.        ],
        [0.        ],
        [0.        ],
        ...,
        [0.05017025],
        [0.023009

In [3]:
x_train,x_test=[],[]
aux=[]
for i in range(len(x)):
    aux=[]
    for j in range(len(x[i])):
        aux.append(x[i][j][0])
    aux/=sum(aux)
    x_train.append(aux)


aux=[]
for i in range(1700,len(y)):
    aux.append(y[i][0])
x_test.append(aux)


data_array=np.array(x_train)
data_array_test=np.array(x_test)
labels_array=np.array([100,150,200,250,300,350,400])
labels_array_test=np.array([280])


print('Numero de espetros: '+ str(len(data_array)))
print('Numero de bins em cada espetro: '+str(len(data_array[0])))
print(data_array)
print('\n')
print(labels_array)

Numero de espetros: 7
Numero de bins em cada espetro: 1878
[[0.00000000e+00 0.00000000e+00 0.00000000e+00 ... 6.06968309e-08
  2.78375248e-08 1.10629008e-08]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 ... 4.03530593e-08
  1.85072148e-08 7.35494565e-09]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 ... 3.01811972e-08
  1.38420707e-08 5.50097240e-09]
 ...
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 ... 2.00092965e-08
  9.17690889e-09 3.64699210e-09]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 ... 1.71030069e-08
  7.84399071e-09 3.11727756e-09]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 ... 1.49232669e-08
  6.84429164e-09 2.71998750e-09]]


[100 150 200 250 300 350 400]


In [11]:
from tensorflow import keras
model=keras.models.Sequential(
    [keras.layers.Dense(64,activation='relu',input_shape=(1878,)),
     keras.layers.Dense(32,activation='relu'),
     keras.layers.Dense(1,activation='sigmoid')]
     )

model.compile(
    loss='Poisson', optimizer='adam', metrics=['accuracy']
)

In [12]:
model.summary()

Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_6 (Dense)             (None, 64)                120256    
                                                                 
 dense_7 (Dense)             (None, 32)                2080      
                                                                 
 dense_8 (Dense)             (None, 1)                 33        
                                                                 
Total params: 122369 (478.00 KB)
Trainable params: 122369 (478.00 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [14]:
model.fit(data_array,labels_array,epochs=500,batch_size=32)

Epoch 1/500
1/1 [==============================] - 0s 7ms/step - loss: 1.0471 - accuracy: 0.0000e+00
Epoch 2/500
1/1 [==============================] - 0s 4ms/step - loss: 1.0469 - accuracy: 0.0000e+00
Epoch 3/500
1/1 [==============================] - 0s 7ms/step - loss: 1.0466 - accuracy: 0.0000e+00
Epoch 4/500
1/1 [==============================] - 0s 8ms/step - loss: 1.0464 - accuracy: 0.0000e+00
Epoch 5/500
1/1 [==============================] - 0s 11ms/step - loss: 1.0461 - accuracy: 0.0000e+00
Epoch 6/500
1/1 [==============================] - 0s 7ms/step - loss: 1.0459 - accuracy: 0.0000e+00
Epoch 7/500
1/1 [==============================] - 0s 5ms/step - loss: 1.0457 - accuracy: 0.0000e+00
Epoch 8/500
1/1 [==============================] - 0s 6ms/step - loss: 1.0454 - accuracy: 0.0000e+00
Epoch 9/500
1/1 [==============================] - 0s 7ms/step - loss: 1.0452 - accuracy: 0.0000e+00
Epoch 10/500
1/1 [==============================] - 0s 6ms/step - loss: 1.0450 - accuracy:

In [7]:
preds= model.predict(x_test)
accuracy_score(y_test,preds.round())

ValueError: in user code:

    File "c:\Users\be_so\AppData\Local\Programs\Python\Python39\lib\site-packages\keras\src\engine\training.py", line 2341, in predict_function  *
        return step_function(self, iterator)
    File "c:\Users\be_so\AppData\Local\Programs\Python\Python39\lib\site-packages\keras\src\engine\training.py", line 2327, in step_function  **
        outputs = model.distribute_strategy.run(run_step, args=(data,))
    File "c:\Users\be_so\AppData\Local\Programs\Python\Python39\lib\site-packages\keras\src\engine\training.py", line 2315, in run_step  **
        outputs = model.predict_step(data)
    File "c:\Users\be_so\AppData\Local\Programs\Python\Python39\lib\site-packages\keras\src\engine\training.py", line 2283, in predict_step
        return self(x, training=False)
    File "c:\Users\be_so\AppData\Local\Programs\Python\Python39\lib\site-packages\keras\src\utils\traceback_utils.py", line 70, in error_handler
        raise e.with_traceback(filtered_tb) from None
    File "c:\Users\be_so\AppData\Local\Programs\Python\Python39\lib\site-packages\keras\src\engine\input_spec.py", line 298, in assert_input_compatibility
        raise ValueError(

    ValueError: Input 0 of layer "sequential" is incompatible with the layer: expected shape=(None, 1878), found shape=(None, 178)
